// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUyCjkctw5aEQ2KSduXt0JfwN-cSq4bSU',
    appId: '1:735959508002:web:530ecbcff931ee3283967b',
    messagingSenderId: '735959508002',
    projectId: 'management-5ac07',
    authDomain: 'management-5ac07.firebaseapp.com',
    databaseURL: 'https://management-5ac07-default-rtdb.firebaseio.com',
    storageBucket: 'management-5ac07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1iQTW9ihiAKgw66gFr7L_ny2bmLh4T8',
    appId: '1:735959508002:android:cd1792116956b1bb83967b',
    messagingSenderId: '735959508002',
    projectId: 'management-5ac07',
    databaseURL: 'https://management-5ac07-default-rtdb.firebaseio.com',
    storageBucket: 'management-5ac07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATFBexGndo3cm6N_AGYgR9776JA5kacrk',
    appId: '1:735959508002:ios:0d5c8ecbfba99c4683967b',
    messagingSenderId: '735959508002',
    projectId: 'management-5ac07',
    databaseURL: 'https://management-5ac07-default-rtdb.firebaseio.com',
    storageBucket: 'management-5ac07.appspot.com',
    iosClientId: '735959508002-9n97f3ib9v1e9l1o5rf2d34af1fvgpmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentcomplainmanagementsys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATFBexGndo3cm6N_AGYgR9776JA5kacrk',
    appId: '1:735959508002:ios:7e2c8f79b725d67583967b',
    messagingSenderId: '735959508002',
    projectId: 'management-5ac07',
    databaseURL: 'https://management-5ac07-default-rtdb.firebaseio.com',
    storageBucket: 'management-5ac07.appspot.com',
    iosClientId: '735959508002-glmh4v7tctm92bir9iuiidg9k4kp5h3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentcomplainmanagementsys.RunnerTests',
  );
}
